# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd943e54040a70e53be8d0861b68594a293ce428d9362623aff00b7c0a94f581df190e5cf5de01ce79e4ea0464ce5fe560781a28bcd7f0b6fd43dde04f8433ea

test:
  secret_key_base: e5f77cca8586a111a68781b481cb8a73b4b84dd1f2fd7cd5d67ffff9e687087fc59a244ff7363ba45a8cd29ccda9a053d555cc1765f464b681f659d17638d292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
